version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_server
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  client:
    container_name: ampq_app
    build: .
    ports:
      - "8080:8080"
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.datasource.url: "jdbc:h2:file:/amqp/db"
    volumes:
      - "C:/dev/amqp/db:/amqp/db"