version: "3.9"
services:
  client:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      FLASK_ENV: development
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"