GET localhost:8080/api/health-check
###

POST localhost:8080/api/sendRequest
Content-Type: application/json

{
  "currencyCode": "EUR",
  "dateTime": "2022-04-10T07:29:54.058"
}
###

GET localhost:8080/api/getProcessingResults